development:
  dialect: postgres
  database: d9h491ekd1fivo
  user: oeiaqbpkqjudhj
  password: 7b6b569040fe1282f5c6bc03f9c908b2a8494117c0104c8051bd3bd6eda2ab40
  host: ec2-107-21-224-76.compute-1.amazonaws.com
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://oeiaqbpkqjudhj:7b6b569040fe1282f5c6bc03f9c908b2a8494117c0104c8051bd3bd6eda2ab40@ec2-107-21-224-76.compute-1.amazonaws.com:5432/d9h491ekd1fivo"}}
  #url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/buffalo_app_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://azureuser@kulado:tr7VUZ9w@kulado.postgres.database.azure.com:5432/postgres?sslmode=disable"}}
