development:
  dialect: postgres
  database: buffalo_app_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/buffalo_app_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://azureuser@kulado:tr7VUZ9w@kulado.postgres.database.azure.com:5432/postgres?sslmode=disable"}}
